/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jaye' at '1/18/15 4:18 PM' with Gradle 2.2.1
 *
 * @author jaye, @date 1/18/15 4:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
